export const COLOR_A = "#FF4757"; // Red
export const COLOR_B = "#1E90FF"; // Blue
export const BACKGROUND_COLOR = "#FFFFFF";
export const INITIAL_SPEED = 5;
export const MAX_SPEED = 20;
export const SPEED_INCREMENT = 0.5;
export const SECTIONS_FOR_SPEED_INCREASE = 5;
export const BALL_RADIUS = 20;
export const PATH_WIDTH = 100;
export const MIN_SECTION_LENGTH = 300;
export const MAX_SECTION_LENGTH = 800;
